/**
 * Copies build artifacts into fluixi-webcomponents after a successful build.
 *
 * Targets
 * ───────────────────────────────────────────────────────────────────────────
 *  flx-icon
 *    cdn/fluixi-icons-all.js  →  flx-icon/src/registry.js
 *    cdn/fluixi-icons-all.js  →  flx-icon/dist/src/registry.js
 *    sprites/*.svg            →  flx-icon/dist/src/sprites/
 *    sprites/*.json           →  flx-icon/dist/src/sprites/
 *
 *  react (React wrappers — icons/  generated by generate-modules.ts,
 *         dist/icons/ built by the react package itself)
 *    react/dist/icons/        →  react/dist/icons/   (already in place after build)
 *    Note: react/icons/*.tsx are written directly by generate-modules.ts so no
 *    extra copy is needed for those; we only sync the built dist artefacts here.
 *
 * On GitHub CI both repos are checked out side-by-side so the relative
 * paths resolve correctly (see update-icons.yml).
 *
 * Usage: tsx scripts/copy-registry.ts
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const WC_BASE = path.resolve(
  __dirname,
  "../../libs/fluixi-webcomponents/packages/components",
);
const FLX_ICON = path.join(WC_BASE, "flx-icon");
const REACT     = path.join(WC_BASE, "react");

// ─── helpers ────────────────────────────────────────────────────────────────

function copy(src: string, dest: string): void {
  if (!fs.existsSync(src)) {
    console.warn(`  [skip] not found: ${path.relative(ROOT, src)}`);
    return;
  }
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
  const rel = (p: string) => path.relative(path.dirname(ROOT), p);
  console.log(`  ✓ ${rel(src)} → ${rel(dest)}`);
}

function copyDir(src: string, dest: string, filter: (name: string) => boolean): void {
  if (!fs.existsSync(src)) {
    console.warn(`  [skip] dir not found: ${path.relative(ROOT, src)}`);
    return;
  }
  fs.mkdirSync(dest, { recursive: true });
  for (const file of fs.readdirSync(src)) {
    if (filter(file)) copy(path.join(src, file), path.join(dest, file));
  }
}

function copyDirRecursive(src: string, dest: string): void {
  if (!fs.existsSync(src)) {
    console.warn(`  [skip] dir not found: ${path.relative(ROOT, src)}`);
    return;
  }
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDirRecursive(s, d);
    else copy(s, d);
  }
}

// ─── flx-icon ───────────────────────────────────────────────────────────────

console.log("\n── flx-icon ──────────────────────────────────────────────────");

const registryBlob = path.join(ROOT, "cdn", "fluixi-icons-all.js");
copy(registryBlob, path.join(FLX_ICON, "src",      "registry.js"));
copy(registryBlob, path.join(FLX_ICON, "dist/src", "registry.js"));

const spritesDir        = path.join(ROOT,    "sprites");
const flxIconSpritesDir = path.join(FLX_ICON, "dist/src/sprites");
copyDir(spritesDir, flxIconSpritesDir, (f) => f.endsWith(".svg") || f.endsWith(".json"));

// ─── react ──────────────────────────────────────────────────────────────────
// generate-modules.ts already writes react/icons/*.tsx directly.
// Here we copy the compiled dist/icons/ output so the published package is
// up-to-date without requiring a separate build step in this script.

console.log("\n── react ─────────────────────────────────────────────────────");

const reactDistIcons = path.join(REACT, "dist", "icons");
if (fs.existsSync(reactDistIcons)) {
  console.log(`  ✓ dist/icons already present (built by react package)`);
} else {
  console.warn(
    `  [info] react/dist/icons not found — run the react package build first`,
  );
}

// Copy sprites into react dist so React consumers can also reference them
const reactSpritesDir = path.join(REACT, "dist", "sprites");
copyDir(spritesDir, reactSpritesDir, (f) => f.endsWith(".svg") || f.endsWith(".json"));

console.log("\n✅ Done. fluixi-webcomponents is up to date.");
